server:
  port: 8083

spring:
  application:
    name:  warehouse-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonal_micro
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: warehouse
    open-in-view: false
  flyway:
    enabled: true
    schemas: warehouse
    default-schema: warehouse
    locations: classpath:db/migration/warehouse
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id:  warehouse-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ecommerce.warehouse.infrastructure.adapter.in.kafka.CatalogProductEvent

management:
  endpoints:
    web:
      exposure:
        include: health, info
